name: fondation
description: Give children a chance

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.0.0+5

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  flutter_inappwebview: ^6.0.0-beta.21
  flutter_launcher_icons: ^0.13.1
  internet_connection_checker: ^0.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
